sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - stable
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm i -g npm@^3.0.0
before_script:
  - npm prune
  - npm run clean
script:
  - npm run lint
  - npm test
after_success:
  - npm run semantic-release
branches:
  only: master
